[package]
name = "mfu-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
rmp = { workspace = true }
duckdb = { workspace = true }
reed-solomon-erasure = { workspace = true }
highway = { workspace = true }
xxhash-rust = { workspace = true }
tracing = { workspace = true }
nix = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { workspace = true }

[dev-dependencies]
tempfile = "3"
