[package]
name = "s3-server"
version = "0.1.0"
edition = "2021"

[dependencies]
mfu-core = { path = "../mfu-core" }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
s3s = { workspace = true }
s3s-aws = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
clickhouse = { workspace = true }
time = "0.3"
mime = "0.3"
async-trait = "0.1"
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { workspace = true }
